sudo: required
dist: trusty

addons:
  apt:
    update: true

language: python
python:
  - "3.6.5"

install:
  # based on http://conda.pydata.org/docs/travis.html and https://github.com/tflearn/tflearn/blob/master/.travis.yml
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy
  - source activate test-environment
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install pil;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      conda install Pillow;
    fi
  - pip3 install tensorflow
  - pip3 list

script:
  - python3 --version
  - python --version
  - which python3
  - which python
  - pip3 list
  - python main.py
